[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.GAME.pack_choices = self.config.center.config.choose or 1"
position = "after"
payload = "G.GAME.selected_back:trigger_effect({context = 'booster'})"
match_indent = true


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local _size = self.ability.extra"
position = "after"
payload = "_size = (G.GAME.selected_back:trigger_effect({context = 'booster2', size = _size}) or _size)"
match_indent = true

