[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.RESET_JIGGLES = true"
position = "after"
payload = '''
if G.GAME.chips - G.GAME.blind.chips >= 0 then
  G.GAME.selected_back:trigger_effect({context = 'mist_end'})
end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.blind:set_blind(G.GAME.round_resets.blind)"
position = "after"
payload = "G.GAME.selected_back:trigger_effect({context = 'mist_start'})"
match_indent = true




